export const theme = {
    'common.bi.image': 'https://uicdn.toast.com/toastui/img/tui-image-editor-bi.png',
    'common.bisize.width': '251px',
    'common.bisize.height': '21px',
    'common.backgroundImage': 'none',
    'common.backgroundColor': '#ffffff',
    'common.border': '0px',

    // header
    'header.backgroundImage': 'none',
    'header.backgroundColor': 'transparent',
    'header.border': '0px',

    // load button
    'loadButton.backgroundColor': '#fff',
    'loadButton.border': '1px solid #ddd',
    'loadButton.color': '#222',
    'loadButton.fontFamily': 'NotoSans, sans-serif',
    'loadButton.fontSize': '12px',

    // download button
    'downloadButton.backgroundColor': '#777777',
    'downloadButton.border': '1px solid #fff',
    'downloadButton.color': '#fff',
    'downloadButton.fontFamily': 'NotoSans, sans-serif',
    'downloadButton.fontSize': '12px',

    // icons default
    'menu.normalIcon.color': '#8a8a8a',
    'menu.activeIcon.color': '#555555',
    'menu.disabledIcon.color': '#434343',
    'menu.hoverIcon.color': '#e9e9e9',
    'submenu.normalIcon.color': '#313131',
    'submenu.activeIcon.color': '#e9e9e9',

    'menu.iconSize.width': '24px',
    'menu.iconSize.height': '24px',
    'submenu.iconSize.width': '32px',
    'submenu.iconSize.height': '32px',

    // submenu primary color
    'submenu.backgroundColor': '#777777',
    'submenu.partition.color': '#858585',

    // submenu labels
    'submenu.normalLabel.color': '#858585',
    'submenu.normalLabel.fontWeight': 'lighter',
    'submenu.activeLabel.color': '#fff',
    'submenu.activeLabel.fontWeight': 'lighter',

    // checkbox style
    'checkbox.border': '1px solid #ccc',
    'checkbox.backgroundColor': '#fff',

    // rango style
    'range.pointer.color': '#fff',
    'range.bar.color': '#666',
    'range.subbar.color': '#d1d1d1',

    'range.disabledPointer.color': '#414141',
    'range.disabledBar.color': '#282828',
    'range.disabledSubbar.color': '#414141',

    'range.value.color': '#fff',
    'range.value.fontWeight': 'lighter',
    'range.value.fontSize': '11px',
    'range.value.border': '1px solid #353535',
    'range.value.backgroundColor': '#151515',
    'range.title.color': '#fff',
    'range.title.fontWeight': 'lighter',

    // colorpicker style
    'colorpicker.button.border': '1px solid #1e1e1e',
    'colorpicker.title.color': '#fff'
};

export const locale_ru = {
    // override default English locale to your custom
    '3:2': '3:2',
    '4:3': '4:3',
    '5:4': '5:4',
    '7:5': '7:5',
    '16:9': '16:9',
    Apply: 'Применить',
    Arrow: 'Arrow',
    'Arrow-2': 'Arrow-2',
    'Arrow-3': 'Arrow-3',
    'Blend': 'Микс',
    'Blur': 'Размытие',
    'Bold': 'Bold',
    'Brightness': 'Яркость',
    'Bubble': 'Bubble',
    'Cancel': 'Отменить',
    'Center': 'Центр',
    'Circle': 'Окружность',
    'Color': 'Цвет',
    'Color Filter': 'Фильтр цвета',
    'Crop': 'Вырезать',
    'Custom': 'Custom',
    'Custom icon': 'Custom icon',
    'Delete': 'Удалить',
    'Delete-all': 'Удалить все',
    'Distance': 'Distance',
    Download: 'Сохранить',
    'Draw': 'Draw',
    'Emboss': 'Emboss',
    'Fill': 'Залить',
    'Filter': 'Фильтр',
    'Flip': 'Flip',
    'Flip X': 'Flip X',
    'Flip Y': 'Flip Y',
    'Free': 'Free',
    'Grayscale': 'Серым',
    'Heart': 'Сердце',
    'Icon': 'Icon',
    'Invert': 'Инверсия',
    'Italic': 'Курсив',
    'Left': 'Left',
    Load: 'Загрузка',
    'Load Mask Image': 'Загрузить маску',
    'Location': 'Location',
    'Mask': 'Маска',
    'Multiply': 'Multiply',
    'Noise': 'Шум',
    'Pixelate': 'Мозаика',
    'Polygon': 'Полигон',
    'Range': 'Угол',
    'Rectangle': 'Rectangle',
    'Redo': 'Повтор',
    'Remove White': 'Убрать белый',
    'Reset': 'Сброс',
    'Right': 'Right',
    'Rotate': 'Поворот',
    'Sepia': 'Сепия',
    'Sepia2': 'Сепия-2',
    'Shape': 'Фигура',
    'Sharpen': 'Sharpen',
    'Square': 'Square',
    'Star-1': 'Star-1',
    'Star-2': 'Star-2',
    'Straight': 'Straight',
    'Stroke': 'Stroke',
    'Text': 'Текст',
    'Text size': 'Размер текста',
    'Threshold': 'Толщина',
    'Tint': 'Tint',
    'Triangle': 'Треугольник',
    'Underline': 'Подчеркивание',
    'Undo': 'Отмена',
    'Value': 'Значение',
}